CFLAGS= -Wall -fpic -coverage -lm -std=c99

rngs.o: rngs.h rngs.c
	gcc -c rngs.c -g  $(CFLAGS)

dominion.o: dominion.h dominion.c rngs.o
	gcc -c dominion.c -g  $(CFLAGS)

playdom: dominion.o playdom.c
	gcc -o playdom playdom.c -g dominion.o rngs.o $(CFLAGS)
#To run playdom you need to entere: ./playdom <any integer number> like ./playdom 10*/
testDrawCard: testDrawCard.c dominion.o rngs.o
	gcc  -o testDrawCard -g  testDrawCard.c dominion.o rngs.o $(CFLAGS)

badTestDrawCard: badTestDrawCard.c dominion.o rngs.o
	gcc -o badTestDrawCard -g  badTestDrawCard.c dominion.o rngs.o $(CFLAGS)

testBuyCard: testDrawCard.c dominion.o rngs.o
	gcc -o testDrawCard -g  testDrawCard.c dominion.o rngs.o $(CFLAGS)

testAll: dominion.o testSuite.c
	gcc -o testSuite testSuite.c -g  dominion.o rngs.o $(CFLAGS)

interface.o: interface.h interface.c
	gcc -c interface.c -g  $(CFLAGS)

runtests: testDrawCard 
	./testDrawCard &> unittestresult.out
	gcov dominion.c >> unittestresult.out
	cat dominion.c.gcov >> unittestresult.out


player: player.c interface.o
	gcc -o player player.c -g  dominion.o rngs.o interface.o $(CFLAGS)

all: playdom player 

unittestresults: unittest1.c unittest2.c unittest3.c unittest4.c cardtest1.c cardtest2.c cardtest3.c cardtest4.c dominion.c rngs.c
	echo "Result for running unit tests:" > unittestresults.out
	echo "unittest1.c:" >> unittestresults.out
	gcc -o unittest1 -g unittest1.c dominion.c rngs.c -coverage -lm
	./unittest1 >> unittestresults.out
	gcov dominion.c >> unittestresults.out

	echo "unittest2.c:" >> unittestresults.out
	gcc -o unittest2 -g unittest2.c dominion.c rngs.c -coverage -lm
	./unittest2 >> unittestresults.out
	gcov dominion.c >> unittestresults.out
  
	echo "unittest3.c:" >> unittestresults.out
	gcc -o unittest3 -g unittest3.c dominion.c rngs.c -coverage -lm
	./unittest3 >> unittestresults.out
	gcov dominion.c >> unittestresults.out
  
	echo "unittest4.c:" >> unittestresults.out
	gcc -o unittest4 -g unittest4.c dominion.c rngs.c -coverage -lm
	./unittest4 >> unittestresults.out
	gcov dominion.c >> unittestresults.out
  
	echo "cardtest1.c:" >> unittestresults.out
	gcc -o cardtest1 -g cardtest1.c dominion.c rngs.c -coverage -lm
	./cardtest1 >> unittestresults.out
	gcov dominion.c >> unittestresults.out

	echo "cardtest2.c:" >> unittestresults.out
	gcc -o cardtest2 -g cardtest2.c dominion.c rngs.c -coverage -lm
	./cardtest2 >> unittestresults.out
	gcov dominion.c >> unittestresults.out

	echo "cardtest3.c:" >> unittestresults.out
	gcc -o cardtest3 -g cardtest3.c dominion.c rngs.c -coverage -lm
	./cardtest3 >> unittestresults.out
	gcov dominion.c >> unittestresults.out

	echo "cardtest4.c:" >> unittestresults.out
	gcc -o cardtest4 -g cardtest4.c dominion.c rngs.c -coverage -lm
	./cardtest4 >> unittestresults.out
	gcov dominion.c >> unittestresults.out

unittest1: unittest1.c dominion.c rngs.c
	gcc -o unittest1 -g unittest1.c dominion.c rngs.c -lm
  
unittest2: unittest2.c dominion.c rngs.c
	gcc -o unittest2 -g unittest2.c dominion.c rngs.c -lm
  
unittest3: unittest3.c dominion.c rngs.c
	gcc -o unittest3 -g unittest3.c dominion.c rngs.c -lm
  
unittest4: unittest4.c dominion.c rngs.c
	gcc -o unittest4 -g unittest4.c dominion.c rngs.c -lm
  
cardtest1: cardtest1.c dominion.c rngs.c
	gcc -o cardtest1 -g cardtest1.c dominion.c rngs.c -lm

cardtest2: cardtest2.c dominion.c rngs.c
	gcc -o cardtest2 -g cardtest2.c dominion.c rngs.c -lm

cardtest3: cardtest3.c dominion.c rngs.c
	gcc -o cardtest3 -g cardtest3.c dominion.c rngs.c -lm
  
cardtest4: cardtest4.c dominion.c rngs.c
	gcc -o cardtest4 -g cardtest4.c dominion.c rngs.c -lm

randomtestresults: randomtestadventurer.c dominion.c rngs.c
	echo "Result for running random tests:" > randomtestresults.out
	echo " " >> randomtestresults.out
	echo "--------------------------------------------------------------------------------------------" >> randomtestresults.out
	echo "randomtestadventurer.c:" >> randomtestresults.out
	gcc -o randomtestadventurer -g randomtestadventurer.c dominion.c rngs.c -coverage -lm
	./randomtestadventurer >> randomtestresults.out
	echo " " >> randomtestresults.out
	gcov dominion.c -f -b >> randomtestresults.out

	echo " " >> randomtestresults.out
	echo "--------------------------------------------------------------------------------------------" >> randomtestresults.out
	echo "randomtestcard1.c:" >> randomtestresults.out
	gcc -o randomtestcard1 -g randomtestcard1.c dominion.c rngs.c -coverage -lm
	./randomtestcard1 >> randomtestresults.out
	echo " " >> randomtestresults.out
	gcov dominion.c -f -b >> randomtestresults.out
  
	echo " " >> randomtestresults.out
	echo "--------------------------------------------------------------------------------------------" >> randomtestresults.out
	echo "randomtestcard2.c:" >> randomtestresults.out
	gcc -o randomtestcard2 -g randomtestcard2.c dominion.c rngs.c -coverage -lm
	./randomtestcard2 >> randomtestresults.out
	echo " " >> randomtestresults.out
	gcov dominion.c -f -b >> randomtestresults.out

randomtestadventurer: randomtestadventurer.c dominion.c rngs.c
	gcc -o randomtestadventurer -g randomtestadventurer.c dominion.c rngs.c -lm

randomtestcard1: randomtestcard1.c dominion.c rngs.c
	gcc -o randomtestcard1 -g randomtestcard1.c dominion.c rngs.c -lm

randomtestcard2: randomtestcard2.c dominion.c rngs.c
	gcc -o randomtestcard2 -g randomtestcard2.c dominion.c rngs.c -lm

clean:
	rm -f *.o playdom.exe playdom player player.exe  *.gcov *.gcda *.gcno *.so *.out testDrawCard testDrawCard.exe unittest1 unittest2 unittest3 unittest4 cardtest1 cardtest2 cardtest3 cardtest4 randomtestadventurer randomtestcard1 randomtestcard2
